# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('item_quantity', models.PositiveIntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=17)),
                ('is_paid', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockItem')),
            ],
        ),
    ]
