# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_id',
            new_name='item',
        ),
    ]
