# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160326_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paied',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
