# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paied',
            new_name='is_paid',
        ),
    ]
